# log dir
log_dir: logs/test
lmdb: false
mode: text
dry_run: false
model_name: 'ds'
inter: 'none'
task_target: " "
save_avg: True

vit_name: 'vit_tiny_patch16_224'
train_set: 'ori'
num_quires: 128
fusion_map: {0: 0, 1: 1, 2: 8, 3: 15}
clip_model_name: "ViT-L/14"

device: 'cpu'
mlp_dim: 256
mlp_out_dim: 128
head_num: 16

# datasets
all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
train_dataset: [FaceForensics++]
#test_dataset: [datasets/Celeb-DF-v1, datasets/Celeb-DF-v2, datasets/DFDCP, datasets/DFDC, datasets/DeepFakeDetection]
#test_dataset: [Celeb-DF-v1]

dataset_json_folder: dataset_jsons  # can leave empty if you don't have JSON metadata

compression: c23
train_batchSize: 20
#test_batchSize: 8
#workers: 2  # reduce for local testing
#frame_num: {'train': 32, 'test': 32}
resolution: 256
with_mask: true
with_xray: true
with_patch_labels: true
with_landmark: false

# labels (keep the same)
label_dict:
  '0-real': 0
  '1-fake': 1

# optimizer
optimizer:
  type: adam
  adam:
    lr: 0.0002
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
    weight_decay: 0.0005
    amsgrad: false

# training
nEpochs: 60
start_epoch: 0
save_epoch: 2
rec_iter: 100
logdir: logs/Ablation

manualSeed: 1020
save_ckpt: true
save_feat: false

# metric
metric_scoring: auc

# cuda
ngpu: 1
cuda: false
cudnn: false

# Data augmentation
data_aug:
  flip_prob: 0.5
  rotate_limit: 30
  rotate_prob: 0.5
  blur_limit: 3
  blur_prob: 0.5
  brightness_limit: 0.2
  contrast_limit: 0.2
  quality_lower: 40
  quality_upper: 100

use_data_augmentation: false

# Normalization
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

test_dataset: [Celeb-DF-v1-mini]
frame_num: {'train': 32, 'test': 32}
test_batchSize: 2
workers: 0
